name: CI

# Trigger this workflow on push or pull request
on: [push, pull_request]

env:
  SRC_DIR_PATH: desktop_version

jobs:
  build-mac:
    name: Build (macos-latest)

    runs-on: macos-latest

    env:
      CXXFLAGS: -I/usr/local/include/SDL2
      LDFLAGS: -L/usr/local/lib

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: brew install ninja sdl2 sdl2_mixer

    - name: CMake configure (default version)
      run: |
        mkdir ${SRC_DIR_PATH}/build && cd ${SRC_DIR_PATH}/build
        cmake -GNinja ..
    - name: Build (default version)
      run: ninja -C ${SRC_DIR_PATH}/build

    - name: CMake configure (official)
      run: |
        cd ${SRC_DIR_PATH}/build
        cmake -DOFFICIAL_BUILD=ON ..
    - name: Build (official)
      run: |
        ninja -C ${SRC_DIR_PATH}/build

    - name: CMake configure (M&P)
      run: |
        cd ${SRC_DIR_PATH}/build
        cmake -DOFFICIAL_BUILD=OFF -DMAKEANDPLAY=ON ..
    - name: Build (M&P)
      run: ninja -C ${SRC_DIR_PATH}/build

    - name: CMake configure (no custom levels)
      run: |
        cd ${SRC_DIR_PATH}/build
        cmake -DMAKEANDPLAY=OFF -DCUSTOM_LEVEL_SUPPORT=DISABLED ..
    - name: Build (no custom levels)
      run: ninja -C ${SRC_DIR_PATH}/build

    - name: CMake configure (no editor)
      run: |
        cd ${SRC_DIR_PATH}/build
        cmake -DCUSTOM_LEVEL_SUPPORT=NO_EDITOR ..
    - name: Build (no editor)
      run: ninja -C ${SRC_DIR_PATH}/build

  build-lin:
    name: Build (CentOS 7)

    runs-on: ubuntu-latest
    container: ghcr.io/leo60228/vvvvvv-build@sha256:485448ad437653d47ceb068a0f2b910f4eb336107d340a1f0d828ca95c987985

    env:
      CXXFLAGS: -I/usr/local/include/SDL2
      LDFLAGS: -L/usr/local/lib

    steps:
    - uses: actions/checkout@v1

    - name: CMake configure (default version)
      run: |
        mkdir ${SRC_DIR_PATH}/build && cd ${SRC_DIR_PATH}/build
        cmake ..
    - name: Build (default version)
      run: make -j $(nproc) -C ${SRC_DIR_PATH}/build

    - name: CMake configure (official)
      run: |
        cd ${SRC_DIR_PATH}/build
        cmake -DOFFICIAL_BUILD=ON ..
    - name: Build (official)
      run: |
        make -j $(nproc) -C ${SRC_DIR_PATH}/build

    - name: CMake configure (M&P)
      run: |
        cd ${SRC_DIR_PATH}/build
        cmake -DOFFICIAL_BUILD=OFF -DMAKEANDPLAY=ON ..
    - name: Build (M&P)
      run: make -j $(nproc) -C ${SRC_DIR_PATH}/build

    - name: CMake configure (no custom levels)
      run: |
        cd ${SRC_DIR_PATH}/build
        cmake -DMAKEANDPLAY=OFF -DCUSTOM_LEVEL_SUPPORT=DISABLED ..
    - name: Build (no custom levels)
      run: make -j $(nproc) -C ${SRC_DIR_PATH}/build

    - name: CMake configure (no editor)
      run: |
        cd ${SRC_DIR_PATH}/build
        cmake -DCUSTOM_LEVEL_SUPPORT=NO_EDITOR ..
    - name: Build (no editor)
      run: make -j $(nproc) -C ${SRC_DIR_PATH}/build

  build-win:
    name: Build (Visual Studio 2010)

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies (Windows)
      run: |
        cd third_party
        Invoke-WebRequest -OutFile sdl2.zip https://www.libsdl.org/release/SDL2-devel-2.0.16-VC.zip
        Invoke-WebRequest -OutFile sdl2_mixer.zip https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.4-VC.zip
        Expand-Archive sdl2.zip -DestinationPath .
        Expand-Archive sdl2_mixer.zip -DestinationPath .
        $env:LDFLAGS =  "/LIBPATH:C:\workspace\third_party\SDL2-2.0.16\lib\x86 "
        $env:LDFLAGS +=  "/LIBPATH:C:\workspace\third_party\SDL2_mixer-2.0.4\lib\x86"

    - name: Start container
      shell: cmd
      run: |
        docker run ^
              --rm --name builder -d -it ^
              --workdir "C:\workspace\desktop_version" -v "${{ github.workspace }}:C:\workspace" ^
              -e "LDFLAGS=%LDFLAGS%" --entrypoint C:\Windows\System32\cmd.exe ^
              cwuensch/vs2010:vcexpress

    - name: CMake configure (default version)
      run: |
        docker exec builder cmake -G "Visual Studio 10 2010" -A Win32 `
              -DSDL2_INCLUDE_DIRS="C:\workspace\third_party\SDL2-2.0.16\include C:\workspace\third_party\SDL2_mixer-2.0.4\include" `
              -DSDL2_LIBRARIES="SDL2;SDL2main;SDL2_mixer" .
    - name: Build (default version)
      run: |
        docker exec builder cmake --build .

    - name: CMake configure (official)
      run: |
        docker exec builder cmake -DOFFICIAL_BUILD=ON .
    - name: Build (official)
      run: |
        docker exec builder cmake --build .

    - name: CMake configure (M&P)
      run: |
        docker exec builder cmake -DOFFICIAL_BUILD=OFF -DMAKEANDPLAY=ON .
    - name: Build (M&P)
      run: |
        docker exec builder cmake --build .

    - name: CMake configure (no custom levels)
      run: |
        docker exec builder cmake -DMAKEANDPLAY=OFF -DCUSTOM_LEVEL_SUPPORT=DISABLED .
    - name: Build (no custom levels)
      run: |
        docker exec builder cmake --build .

    - name: CMake configure (no editor)
      run: |
        docker exec builder cmake -DCUSTOM_LEVEL_SUPPORT=NO_EDITOR .
    - name: Build (no editor)
      run: |
        docker exec builder cmake --build .
